'use strict';

/**
 * All filesystem operations for server directory management.
 * Uses only Node.js built-in `fs` and `path` — no external dependencies.
 */

const fs = require('fs');
const path = require('path');

/**
 * Create the server's working directory.
 * Uses { recursive: true } so it's idempotent if called on an existing empty dir,
 * but we check for the dir before calling this to give a nicer error message.
 * @param {string} serverPath  Absolute path to the server directory
 */
function createServerDirectory(serverPath) {
  fs.mkdirSync(serverPath, { recursive: true });
}

/**
 * Write eula.txt with eula=true so Minecraft accepts the EULA automatically.
 * By creating a server through YAMS the user acknowledges the Minecraft EULA:
 * https://aka.ms/MinecraftEULA
 * @param {string} serverPath
 */
function writeEula(serverPath) {
  const content = [
    '#By changing the setting below to TRUE you are indicating your agreement',
    '#to the Minecraft End User License Agreement (https://aka.ms/MinecraftEULA).',
    `#Generated by YAMS on ${new Date().toISOString()}`,
    'eula=true',
  ].join('\n');

  fs.writeFileSync(path.join(serverPath, 'eula.txt'), content, 'utf8');
}

/**
 * Write a minimal server.properties file.
 * Only the settings we care about are set; everything else uses Minecraft defaults.
 * @param {string} serverPath
 * @param {{ port: number, name: string, maxPlayers?: number, motd?: string, gamemode?: string, pvp?: boolean, onlineMode?: boolean }} options
 */
function writeServerProperties(serverPath, { port, name, maxPlayers, motd, gamemode, pvp, onlineMode }) {
  const content = [
    `#Minecraft server properties — generated by YAMS`,
    `#${new Date().toISOString()}`,
    `server-port=${port}`,
    `online-mode=${onlineMode ? 'true' : 'false'}`,
    `motd=${motd || `A YAMS Server - ${name}`}`,
    `max-players=${maxPlayers || 20}`,
    `difficulty=easy`,
    `gamemode=${gamemode || 'survival'}`,
    `pvp=${pvp !== false ? 'true' : 'false'}`,
    `enable-command-block=false`,
    `view-distance=10`,
    `spawn-protection=16`,
  ].join('\n');

  fs.writeFileSync(path.join(serverPath, 'server.properties'), content, 'utf8');
}

/**
 * Check whether server.jar exists in the given server directory.
 * The user must place this file manually before starting the server.
 * @param {string} serverPath
 * @returns {boolean}
 */
function serverJarExists(serverPath) {
  return fs.existsSync(path.join(serverPath, 'server.jar'))
      || fs.existsSync(path.join(serverPath, 'run.sh'));
}

function usesRunScript(serverPath) {
  return fs.existsSync(path.join(serverPath, 'run.sh'));
}

module.exports = {
  createServerDirectory,
  writeEula,
  writeServerProperties,
  serverJarExists,
  usesRunScript,
};
